# Project: trabalho1WallaceMarques
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = operacaoPolinomiosWallaceMarques.o otimizacaoPolinomiosWallaceMarques.o
LINKOBJ  = operacaoPolinomiosWallaceMarques.o otimizacaoPolinomiosWallaceMarques.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = trabalho1WallaceMarques.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

operacaoPolinomiosWallaceMarques.o: operacaoPolinomiosWallaceMarques.c
	$(CC) -c operacaoPolinomiosWallaceMarques.c -o operacaoPolinomiosWallaceMarques.o $(CFLAGS)

otimizacaoPolinomiosWallaceMarques.o: otimizacaoPolinomiosWallaceMarques.c
	$(CC) -c otimizacaoPolinomiosWallaceMarques.c -o otimizacaoPolinomiosWallaceMarques.o $(CFLAGS)
