# Project: trabalho1ExtraWallaceMarques
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = operacaoPolinomiosExtraWallaceMarques.o otimizacaoPolinomiosExtraWallaceMarques.o
LINKOBJ  = operacaoPolinomiosExtraWallaceMarques.o otimizacaoPolinomiosExtraWallaceMarques.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = trabalho1ExtraWallaceMarques.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

operacaoPolinomiosExtraWallaceMarques.o: operacaoPolinomiosExtraWallaceMarques.c
	$(CC) -c operacaoPolinomiosExtraWallaceMarques.c -o operacaoPolinomiosExtraWallaceMarques.o $(CFLAGS)

otimizacaoPolinomiosExtraWallaceMarques.o: otimizacaoPolinomiosExtraWallaceMarques.c
	$(CC) -c otimizacaoPolinomiosExtraWallaceMarques.c -o otimizacaoPolinomiosExtraWallaceMarques.o $(CFLAGS)
